rescue Exception => e
  # ...
end

print